In [2]:
import numpy as np 
from scipy.sparse import csr_matrix
csr_matrix((3, 4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

mydoclist = ['find what you love', 'do what you love', 'do not do what you hate']

tfidf_vectorizer = TfidfVectorizer(min_df=1)
tfidf_matrix = tfidf_vectorizer.fit_transform(mydoclist)

document_distances = (tfidf_matrix * tfidf_matrix.T )

print('유사도 분석을 위한' +  str(document_distances.get_shape()[0]) + 'x' +  str(document_distances.get_shape()[1]) + 'matrix를 만들었습니다.')

print(document_distances)

유사도 분석을 위한3x3matrix를 만들었습니다.
  (0, 2)	0.2065742202202891
  (0, 1)	0.62111187610611
  (0, 0)	0.9999999999999998
  (1, 2)	0.6083238568956406
  (1, 1)	1.0000000000000002
  (1, 0)	0.62111187610611
  (2, 2)	0.9999999999999999
  (2, 1)	0.6083238568956406
  (2, 0)	0.2065742202202891

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

mydoclist = ['위;수 행;거;15v1.1 협력대상국 개발환경;분석;기 XX1 협력대상국;정책;제도;법령;검토;공적개발원조 추진;실현 가능성;분석;수;XX2 협력대상국을;지원;공여자;지원특성;운영전략;실행 방안;파악;한국;비교 우위;도출;수;XX3;한국;협력대상국;이해관계자;분석;원활;협력;수;방안;제시;수;;공적개발원조;협력대상국;국내외 환경;기타 위험요소;조사;실시;사업수행 특이사항;분석;수;지 식;국제기구;양자원조기구;NGO;협력대상국;개발정책;지원현황;지;식;한국;협력대상국 지원 실적;사례현황;지식;협력대상국;법체계;역사;정치경제;국제관계;사회정책;종교;문화;지식;협력대상국;분야;사업 운영 사례;비즈니스 관행;지식;술;다문화 이해능력;영어 의사소통 능력;외국어 독해능력;협력대상국;법;행정체계 분석 능력;태;객관적;논리적;사고;태도;분석적;총괄적;사고;태도;협력적;태도;15v1.2 자국협력환경;분석;XX1 자국;공적개발원조정책;파악;수;XX2 자국;협력대상국;정책;확인;수;XX3 자국;협력대상국;적합;지원 분야;방식;파악;수;지 식;분류번호;15v1 능력단위 명칭;공적개발원조사업 개발전략수립 능력단위 정의;공적개발원조사업 개발전략 수립;협력대상국;정책;제도;법령;현지여건;토대;지원필요성;검토;자국;비교우위;도출;협력대상국;경제;사회개 발;촉진;종합적 지원전략;수립;능력;위;수 행;거;자국;공적개발원조 수행방식;수행기관 업무;지식;자국;공적개발원조 예산;통계;지식;자국;공적개발원조 주요 지원 분야;지식;자국;대외정책;공적개발원조정책;국;협력전략;지식;술;외국어 독해능력;자국;내;공적개발원조 기관;간;소통 능력;협력대상국;법;행정체계 분석 능력;태;객관적;논리적;사고;태도;분석적;총괄적;사고;태도;협력적;태도;15v1.3 협력대상국 지원전략;수립;기 XX1;수립;자국 공적개발원조정책 관계 부처;협력대상국;의견;수 렴;수;XX2 협력대상 개발환경과 자국 지원 환경;문서;작성;수;XX3 협력정책;수행 경과;협력환경 변화;수정;수;지 식;국제기구;양자원조기구;NGO;협력대상국;개발정책;지원현황;지;식;협력대상국;공적개발원조 담당기관;주요 행위자 업무현황;지식;협력대상국;법체계;역사;정치 경제;국제관계;사회정책;종교;문화;지식;협력대상국;분야;사업 운영 사례;비즈니스 관행;지식;술;기획능력;문서 작성능력;영어 의사소통 기술;외국어 독해능력;자료 분석능력;태;객관적;논리적;사고;태도;분석적;총괄적;사고;태도;협력적;태도;적용범위;작업상황 고려사항;능력단위;정부;개발협력 상위 정책방향;업무;적용;능력단위;협력대상국;내부 정책방향;업무;적용;국;협력전략문서;개발협력위원회;중점협력대상국;작성;것;말;능력단위;양자;간;무상원조;기술협력;양자;간;유상원조;다자간 원조;구분;양자;간;무상원조;기술협력;적용;개발전략;유무상 공통;적용;NCS;무상;대상;자료;관련;서류;협력대상국;정부;원조정책;해당 개발도상국;외교전략;자국;개발경험;자료;조사방법론;공여국;지원 사업 현황;자료;협력대상국;개발전략;자료;협력대상국;국제개발목표;MDGs;달성 실적;보고서;협력대상국;빈곤감소정책보고서;PRSP;협력대상국;예산 회계 제도;자료;협력대상국;정부정책평가 제도;자료;협력대상국;행정체계;자료 장비;도구;컴퓨터;스프레드 시트;문서작성;데이터베이스;통계분석 프로그램;프린터;복사기 재료;인쇄;복사 용지;평가지침;평가방법;평가자;능력단위 수행준거;제시;내용;평가;이론;실기;평가;종합;결과물;평가;다양;평가 방법;사용;수;평가자;과정평가;결과평가 방법 평;방 법 평;형 과 정;평;결;평;포트폴리오;문제해결 시나리오;서술형시험;논술형시험;사례연구;평가자 질문;평가자 체크리스트;피평가자 체크리스트;일지;저널;역할연기;구두발표;작업장평가;기타;평가;시;고려사항;수행준거;제시;내용;성공적;수행;수;평가;평가자;다음;사항;평가;;협력대상국;개발수요 분석;협력대상국;기관;국제기구;양자기구;NGO;전략 분석;자국;공적개발원조 체계;정책;예산;지식;직업기초능력;번;능 력 주;영 역;위;역;의사소통능력 문서이해 능력;문서작성능력;경청능력;의사표현능력;기초외국어능력;조직;해능력 국제 감각;조직체제 이해능력;조직 구성능력;역할 분담 능력;자원관리능력 시간자원관리능력;예산자원관리능력;물적자원관리능력;인적자원관리능 력;대인관계능력 팀워크능력;리더십능력;신뢰관계 형성능력;갈등관리능력;협상능력;고 객서비스능력;문제해결능력 사고력;문제원인 파악능력;문제처리능력;개발 이력;분;용 직무명칭 공적개발원조사업관리 분류번호;15v1 개발연도;최초;버전번호 v1 개 발 자;한국프로젝트경영협회 최초;한국프로젝트경영협회;향후;보완 연도;예정',
'자기소개서;개인;일대기;지원;분야;직업기초능력;서술;문항;미만;;본인;지원 분야;영업;마케팅 분야;일;품질;사람;제품;사람;제품;행복;기업;성장;수;생각;;;지원;직무;관련;교육;훈련;기술;업무활용방안;말씀;정식;훈련;적;영업;마케팅 분야;다양;책;직무;관련;역량;생각;영업;결과;말;영업;배반;마케팅 불변;법칙;책;물건;때;제품;광고;포장;판매원;대화;관심;;;;;;지원;직무;관련;경력;활동;직무;도움;기술;판매일;본격적;적;학교 축제;물건;경험;순대 볶음;것;뿐;재료;준비;것;요리;수;환경;것;그릇;수저;테이블;준비;것;메뉴판;준비;것;접시;필요;것;것;영업 업무;준비;직원;;;지원;직무;관련;본인;능력;장단점;기술;성격;낙관적;긍정적;영향;수;생각;동료 직원;고객;말;말;사람;일;물건;주저;생각;낙관적;성격;때문;도전;실패;것;단점;수;실패;성장;수;기회;;;;지원;직무;수행;필요;윤리의식;본인;윤리 의식;부합;윤리;평가;중요;것;정직;생각;고객;물건;이유;물건;때문;사람;일;말;믿음;수;행동;일;영향;것;;;;지원;직무;필요;대인관계 능력;의사소통 능력;생각;본인;능력;피력;가게;분;기억;것;중요;생각;물건;손님;게;부족;귀중;손님;생각;물건;이야기;중요;날씨 얘기;스포츠 경기;이야기;유행;이야기;손님;심리적 거리;의사소통 능력;중요;평소;다양;뉴스;손님;이야기;주제;노력;']
tfidf_vectorizer = TfidfVectorizer(min_df=1)
tfidf_matrix = tfidf_vectorizer.fit_transform(mydoclist)

document_distances = (tfidf_matrix * tfidf_matrix.T )

#print('유사도 분석을 위한' +  str(document_distances.get_shape()[0]) + 'x' +  str(document_distances.get_shape()[1]) + 'matrix를 만들었습니다.')

print(document_distances)

  (0, 1)	0.058623213843642184
  (0, 0)	1.0000000000000016
  (1, 1)	0.9999999999999988
  (1, 0)	0.058623213843642184

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

f = open("C:/Users/user/Desktop/stat.txt", "r", encoding = "utf-8" )
mydoclist_2 = f.readlines()
mydoclist_2

tfidf_vectorizer = TfidfVectorizer(min_df=1)

tfidf_matrix = tfidf_vectorizer.fit_transform(mydoclist_2)

document_distances = (tfidf_matrix * tfidf_matrix.T )

print(type(document_distances))


#dd=np.around(document_distances)

#import math 
#math.ceil(document_distances)

print('유사도 분석을 위한' +  str(document_distances.get_shape()[0]) + 'x' + str(document_distances.get_shape()[1]) + 'matrix를 만들었습니다.')

dd=document_distances.toarray()
print(dd)
#print(document_distances.toarray())

#print(tfidf_matrix)

<class 'scipy.sparse.csr.csr_matrix'>
유사도 분석을 위한9x9matrix를 만들었습니다.
[[1.         0.05627911 0.09057614 0.04163483 0.11239687 0.05437421
  0.07406914 0.02945079 0.03204423]
 [0.05627911 1.         0.17527175 0.0535483  0.12787742 0.08844907
  0.1084543  0.04922988 0.08577422]
 [0.09057614 0.17527175 1.         0.08960475 0.19071247 0.17958105
  0.1999686  0.02002475 0.08844599]
 [0.04163483 0.0535483  0.08960475 1.         0.08305515 0.12859857
  0.05859738 0.03037245 0.1352138 ]
 [0.11239687 0.12787742 0.19071247 0.08305515 1.         0.13689265
  0.17434789 0.04968368 0.12695764]
 [0.05437421 0.08844907 0.17958105 0.12859857 0.13689265 1.
  0.14504957 0.01914913 0.05015258]
 [0.07406914 0.1084543  0.1999686  0.05859738 0.17434789 0.14504957
  1.         0.03360702 0.27170102]
 [0.02945079 0.04922988 0.02002475 0.03037245 0.04968368 0.01914913
  0.03360702 1.         0.04162328]
 [0.03204423 0.08577422 0.08844599 0.1352138  0.12695764 0.05015258
  0.27170102 0.04162328 1.        ]]

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

frame=pd.DataFrame(dd)

print(frame)

frame.rename(index=str, columns={"0": "a", "1": "b", "2": "c", "3": "d", "4": "e",
                                "5": "f", "6": "g", "7": "h", "8": "i"})

          0         1         2         3         4         5         6  \
0  1.000000  0.056279  0.090576  0.041635  0.112397  0.054374  0.074069
1  0.056279  1.000000  0.175272  0.053548  0.127877  0.088449  0.108454
2  0.090576  0.175272  1.000000  0.089605  0.190712  0.179581  0.199969
3  0.041635  0.053548  0.089605  1.000000  0.083055  0.128599  0.058597
4  0.112397  0.127877  0.190712  0.083055  1.000000  0.136893  0.174348
5  0.054374  0.088449  0.179581  0.128599  0.136893  1.000000  0.145050
6  0.074069  0.108454  0.199969  0.058597  0.174348  0.145050  1.000000
7  0.029451  0.049230  0.020025  0.030372  0.049684  0.019149  0.033607
8  0.032044  0.085774  0.088446  0.135214  0.126958  0.050153  0.271701

          7         8
0  0.029451  0.032044
1  0.049230  0.085774
2  0.020025  0.088446
3  0.030372  0.135214
4  0.049684  0.126958
5  0.019149  0.050153
6  0.033607  0.271701
7  1.000000  0.041623
8  0.041623  1.000000

,0,1,2,3,4,5,6,7,8
0,1.000000,0.056279,0.090576,0.041635,0.112397,0.054374,0.074069,0.029451,0.032044
1,0.056279,1.000000,0.175272,0.053548,0.127877,0.088449,0.108454,0.049230,0.085774
2,0.090576,0.175272,1.000000,0.089605,0.190712,0.179581,0.199969,0.020025,0.088446
3,0.041635,0.053548,0.089605,1.000000,0.083055,0.128599,0.058597,0.030372,0.135214
4,0.112397,0.127877,0.190712,0.083055,1.000000,0.136893,0.174348,0.049684,0.126958
5,0.054374,0.088449,0.179581,0.128599,0.136893,1.000000,0.145050,0.019149,0.050153
6,0.074069,0.108454,0.199969,0.058597,0.174348,0.145050,1.000000,0.033607,0.271701
7,0.029451,0.049230,0.020025,0.030372,0.049684,0.019149,0.033607,1.000000,0.041623
8,0.032044,0.085774,0.088446,0.135214,0.126958,0.050153,0.271701,0.041623,1.000000

In [8]:
import numpy as np

a = np.ones((3, 3), dtype=np.float) * 0.1434655

print(a)

for i in range(3):
    for j in range(3):
        a[i, j] = 0.14
        
print(a)

[[0.1434655 0.1434655 0.1434655]
 [0.1434655 0.1434655 0.1434655]
 [0.1434655 0.1434655 0.1434655]]
[[0.14 0.14 0.14]
 [0.14 0.14 0.14]
 [0.14 0.14 0.14]]

In [8]:
print(type(frame))
frame.rename(index=str, columns={"0": "a", "1": "b", "2": "c", "3": "d", "4": "e",
                                "5": "f", "6": "g", "7": "h", "8": "i"})

<class 'pandas.core.frame.DataFrame'>

,0,1,2,3,4,5,6,7,8
0,1.000000,0.056279,0.090576,0.041635,0.112397,0.054374,0.074069,0.029451,0.032044
1,0.056279,1.000000,0.175272,0.053548,0.127877,0.088449,0.108454,0.049230,0.085774
2,0.090576,0.175272,1.000000,0.089605,0.190712,0.179581,0.199969,0.020025,0.088446
3,0.041635,0.053548,0.089605,1.000000,0.083055,0.128599,0.058597,0.030372,0.135214
4,0.112397,0.127877,0.190712,0.083055,1.000000,0.136893,0.174348,0.049684,0.126958
5,0.054374,0.088449,0.179581,0.128599,0.136893,1.000000,0.145050,0.019149,0.050153
6,0.074069,0.108454,0.199969,0.058597,0.174348,0.145050,1.000000,0.033607,0.271701
7,0.029451,0.049230,0.020025,0.030372,0.049684,0.019149,0.033607,1.000000,0.041623
8,0.032044,0.085774,0.088446,0.135214,0.126958,0.050153,0.271701,0.041623,1.000000